# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from function import *
check()
class Ui_MainWindow(object):
    inStatus = "Stopped"
    titleVid = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(30, 90, 75, 23))
        self.play.setObjectName("play")
        self.play.clicked.connect(self.PlayClicked)
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(170, 90, 75, 23))
        self.pause.setObjectName("pause")
        self.pause.clicked.connect(self.PauseClicked)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(310, 90, 75, 23))
        self.stop.setObjectName("stop")
        self.stop.clicked.connect(self.StopClicked)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(10, 120, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.textEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 421, 31))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def PlayClicked(self):
        global titleVid
        titleVid = title(self.textEdit.text())
        self.status.setText("Status: Loading...")
        playVid(self.textEdit.text())
        self.status.setText("Status: Playing "+titleVid)
        global inStatus
        inStatus = "Playing"

    def PauseClicked(self):
        global inStatus, titleVid
        if inStatus == "Playing":
            PauseVid()
            inStatus = "Paused"
            self.status.setText("Status: Paused "+titleVid)
        else:
            unPause()
            inStatus = "Playing"
            self.status.setText("Status: Playing "+titleVid)
    
    def StopClicked(self):
        global inStatus, titleVid
        StopVid()
        inStatus = "Stopped"
        titleVid = ""
        self.status.setText("Status: Stopped")
    
    def UpdaterClicked(self):
        check()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BytinPlay v1.0"))
        self.play.setText(_translate("MainWindow", "Load"))
        self.pause.setText(_translate("MainWindow", "Play/Pause"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Please enter URL (Supports only Youtube):"))
        self.status.setText(_translate("MainWindow", "Status:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
